-- API CONSTANTS (don't change)

WATER = 0
LAND = 1
AIR = 2

YAWLEFT = 0
YAWRIGHT = 1
ROLLLEFT = 2
ROLLRIGHT = 3
NOSEUP = 4
NOSEDOWN = 5
INCREASE = 6
DECREASE = 7
MAINPROPULSION = 8

BALLOON = 0 -- boolean
DRIVEMAINTAINER = 1 -- float
AIRPUMP = 2 -- float/bool
RESOURCEGATHERER = 3 -- boolean
OILDRILL = 4 -- boolean
AMMOPROCESSOR = 5 -- boolean
OILPROCESSOR = 6 -- boolean
TRACTORBEAM = 7 -- boolean
HYDROFOIL = 8 -- float
PROPULSION = 9 -- float
SHIELDPROJECTOR = 10 -- float/int
