-- PROPULSION API CONSTANTS (don't change)

-- luacheck: push ignore 131
WATER = 0
LAND = 1
AIR = 2

-- Used by I:RequestControl
-- TODO Get rid of it
YAWLEFT = 0
YAWRIGHT = 1
ROLLLEFT = 2
ROLLRIGHT = 3
NOSEUP = 4
NOSEDOWN = 5
INCREASE = 6
DECREASE = 7
MAINPROPULSION = 8

-- Used by I:GetDrive
PRIMARY = 0
SECONDARY = 1
TERTIARY = 2

-- Used by I:SetPropulsionRequest
DRIVETYPE_MAIN = 0
DRIVETYPE_SECONDARY = 1
DRIVETYPE_TERTIARY = 2
DRIVETYPE_ROLL = 3
DRIVETYPE_PITCH = 4
DRIVETYPE_YAW = 5
DRIVETYPE_FORWARDS = 6
DRIVETYPE_UP = 7
DRIVETYPE_RIGHT = 8
DRIVETYPE_A = 9
DRIVETYPE_B = 10
DRIVETYPE_C = 11
DRIVETYPE_D = 12
DRIVETYPE_E = 13
-- luacheck: pop
